env:
  node: true
  # browser: true
  # jest: true

# plugins:
#   - jest
#   - testing-library
#   - jest-dom

extends:
  - 'airbnb-base'
  # - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
